from app.magic.Errors import MagicException


class DoormanAuthException(MagicException):
    pass
